### ISSUE TITLE
Original Pluto.jl Styling

### ISSUE THREAD

**Issue by unnamedunknownusername** [rikhuijzer/JuliaTutorialsTemplate#19]
First thanks so much for all the work on this. 

I am in the process of creating a website to host some notebooks.

I would like to disable some the "new" CSS styling built-into the template. (For some background the main reason I gravitated to the template over https://github.com/JuliaPluto/static-export-template was your inclusion of a menu/navbar.) Becasue I really would like the notebook to look like a Pluto notebook (if that makes sense)

could you point me to the correct place? Is there some way to "delete" the "new" styling so that it stops overriding Pluto's defaults?
Or would it be more along the lines of copying the same CSS from Pluto (https://github.com/fonsp/Pluto.jl/blob/main/frontend/editor.css)
into the CSS folders here.

Many thanks in advance.

**Comment by rikhuijzer** [comment]
Thanks for opening an issue.

> could you point me to the correct place? Is there some way to "delete" the "new" styling so that it stops overriding Pluto's defaults?

Actually, this project sidesteps Pluto's defaults completely. All styling is, so to say, "added" back. Making Pluto's original CSS work would mean giving all the right names for the various CSS elements and loading Pluto's default CSS file too. That  was not my intention of this project. The intention of this project is to make webpages based on Pluto where no one would need to know that it is Pluto.

So I think I'm gonna close this issue because it's not in-line with the direction that I have in mind for this project.

**Comment by unnamedunknownusername** [comment]
Thanks for the prompt reply. Not a problem. I actually seem to have misinterpreted the use case of this package. I found https://github.com/greimel/pluto-course-template to suit my use case better. Just thought I would post the info here in case others have a similar use case.
